config/routes.rb
Rails.application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :jobs
  root 'jobs#index'
  get "about" => "pages#about"
  get "myjobs" => "jobs#myjobs"

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :from_url, :allow_nil => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :jobs
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider 
      user.uid      = auth.uid
      user.name     = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def authenticate!
     flash[:alert] = '必須登入才能張貼工作資訊喔'
     redirect_to root_path unless user_signed_in?
  end

  def user_signed_in?
     !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate!,except:[:index,:show]
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def myjobs
    @jobs = current_user.jobs
  end

  def index
    @jobs = Job.where(:published => true).order("created_at DESC")
    render :layout => 'root'
  end

  def show
  end

  def new
    @job = Job.new
  end

  def edit
  end

  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: '已成功更新工作資訊' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end
  def create
    @job = current_user.jobs.build(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: '成功新增工作資訊' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to :jobs, notice: '工作資訊已刪除' }
      format.json { head :no_content }
    end
  end

  private

  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
      params.require(:job).permit(
        :title,:description,:requirement,:job_type,:location,:salary_high,:salary_low,
        :company_name,:company_url,:apply_info,:begginer)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def pages
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    flash[:notice] = '歡迎光臨 Job on Rails !!'
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Bye bye ~ Have a nice day !!'
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def type_label_selector(type)
    case type
    when "Full-time"
      content_tag( :div, "Full-time", :class=>"job-label full-time")
    when "Part-time"
      content_tag( :div, "Part-time", :class=>"job-label part-time")
    when "Intership"
      content_tag( :div, "Internship", :class=>"job-label internship")
    when "Internship"
      content_tag( :div, "Internship", :class=>"job-label internship")
    when "Other"
      content_tag( :div, "Other", :class=>"job-label other")
    end
    
  end
end

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">a Job on Rails</a>
    </div>
    <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=""><a href=<%=about_path%>>關於</a></li>

        <li class=""><a href=<%=new_job_path%>>張貼新工作</a></li>
        <p class="navbar-text pull-right">
          
          <% if current_user %>
            <li>
              <%= link_to current_user.name , myjobs_path%>
            </li>
            <li id="user-widget">
              <%= link_to "登出", signout_path, id: "sign_out" %>
            </li>
          <% else %>
            <li id="user-widget">
            <%= link_to "使用臉書登入", "/auth/facebook", id: "sign_in" %>
            </li>
          <% end %>
          

          </p>
      </ul>
    </div>
  </div>
</nav>

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <div>
    <% if @job.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@form.errors.count, "error") %> 
          prohibited this form from being saved:
        </h2>

        <ul>
        <% @job.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="job_section">
      <div class="field form-group">
        <%= f.label :job_type ,"工作型態" %>
        <%= f.select :job_type, options_for_select([ "Full-time", "Part-time" , "Internship","Other"]) ,class:"form-control"%>
      </div>

      <div class="field form-group">
        <%= f.label :title ,"工作職稱" %><br>
        <%= f.text_field :title ,class:"form-control",placeholder:"ex. Ruby on Rails 工程師"%>
      </div>

      <div class="field form-group">
        <%= f.check_box :begginer%>
        <%= f.label :begginer ,"是否適合新手？" %>
      </div>

      <div class="field form-inline form-group">
        <%= f.label :title ,"薪資範圍（NTD/月）" %><br>
        <div class="field form-group">
          <%= f.text_field :salary_low ,class:"form-control"%>
        </div>
        ~
        <div class="field form-group">
          <%= f.text_field :salary_high ,class:"form-control"%>
        </div>
      </div>

      <div class="field form-group">
        <%= f.label :description ,"工作描述"%><br>
        <%= f.text_area :description , rows:"5",class:"form-control",placeholder:"ex.使用Ruby on Rails 進行新網站設計開發 .."%>
      </div>

      <div class="field form-group">
        <%= f.label :requirement ,"應徵條件"%><br>
        <%= f.text_area :requirement ,class:"form-control", rows:"3",class:"form-control",placeholder:"ex.Ruby on Rails, HTML / JavaScript / CSS, Git.."%>
      </div>

      <div class="field form-group">
        <%= f.label :location,"工作地點" %><br>
        <%= f.text_field :location,class:"form-control",placeholder:"ex.南港軟體園區, 西湖捷運站2號出口..."%>
      </div>

      <div class="field form-group">
        <%= f.label :company_name ,"公司名稱" %><br>
        <%= f.text_field :company_name ,class:"form-control"%>
      </div>

      <div class="field form-group">
        <%= f.label :company_url ,"公司網址/連結" %><br>
        <%= f.text_field :company_url ,class:"form-control"%>
      </div>

      <div class="field form-group">
        <%= f.label :apply_info ,"應徵方式" %><br>
        <%= f.text_field :apply_info ,class:"form-control",placeholder:"ex.將履歷寄送至hr@mycompany.com"%>
      </div>

      <div class="actions">
        <%= f.submit "確認", :class => 'btn btn-success submit-form pull-right'%>
      </div>
    </div>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 page">
    <h1>Edit Job</h1>

    <%= render 'form' %>

    <%= link_to '返回', jobs_path , class:"back-section btn btn-default"%>
  </div>
</div>

app/views/jobs/index.html.erb
<header class="business-header"
  <div class="container">
    <h1 class="tagline">Get a Job on Rails</h1>
  </div>
</header>

<div class="container">
  <div class="col-md-offset-2 col-md-8 list-group">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <% @jobs.each do |job| %>
      <a href="<%= job_path(job) %>" class="list-group-item">
        <%= type_label_selector(job.job_type) %>
        <div class="job-context">
          <h4><%= job.title %></h4>
          <p>
            <span class="glyphicon glyphicon glyphicon-home" aria-hidden="true"></span>
            <%= job.company_name%>
            <span class="glyphicon glyphicon glyphicon-map-marker" aria-hidden="true"></span>
            <%= job.location%>
            <% if job.begginer %>
                <span class="glyphicon glyphicon glyphicon-ok" aria-hidden="true" style="color:#f44336;"></span>
                初學者可
            <% end %>
          </p>

        </div>
      </a>
    <% end %>
  </div>
</div>

app/views/jobs/myjobs.html.erb
<div class="container">
  
  <div class="col-md-offset-2 col-md-8 list-group">
  <h2>Jobs posted by me</h2>
    <% @jobs.each do |job| %>
      <a href="<%= job_path(job) %>" class="list-group-item">
        <%= type_label_selector(job.job_type) %>
        <div class="job-context">
          <h4><%= job.title %></h4>
        </div>
      </a>
    <% end %>
  </div>
</div>

app/views/jobs/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 page">
      <h1>張貼新工作</h1>

      <%= render 'form' %>

      <%= link_to '返回', jobs_path , class:"back-section btn btn-default"%>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="container">
  <div class="col-md-8 col-md-offset-2 page">
    <h2><%= @job.title%></h2>
    <% if current_user && @job.user_id == current_user.id%>
      <p>
        <%= link_to "Edit", edit_job_path(@job), :class=>"btn btn-xs btn-warning"%>
        <%= link_to "Delete",job_path(@job), :confirm => 'Are you sure?', :method => :delete , :class=>"btn btn-xs btn-danger"%>
      </p>
    <%end%>
    <hr>
    <%= type_label_selector(@job.job_type) %>
    <br>
    <br>
    <p>
      <span class="glyphicon glyphicon glyphicon-home" aria-hidden="true"></span>
      <%= link_to @job.company_name , @job.company_url%>
    </p>
    <p>
      <span class="glyphicon glyphicon glyphicon-map-marker" aria-hidden="true"></span>
      <%= @job.location%>
    </p>
    <p>
      <span class="glyphicon glyphicon glyphicon-usd" aria-hidden="true"></span>
      <% if @job.salary_low == 0 and @job.salary_high == 0 %>
      詳情參考工作內容
      <% else %>
      NTD <%= @job.salary_low %> ~ <%= @job.salary_high %>
      <% end %>
    </p>
    <% if @job.begginer %>
      <p>
        <span class="glyphicon glyphicon glyphicon-ok" aria-hidden="true"></span>
        願意接受初學者
      </p>
    <% end %>

    <hr>
    <% if @job.from %>
      <div class="alert alert-success" role="alert">
      <%= "此工作資訊來自 #{@job.from} ,如有資訊不明,"   %>
      <%= link_to "可點此處瀏覽原始資訊", @job.from_url%>
      </div>
    <% end %>
    
    <h3><span class="glyphicon glyphicon glyphicon-calendar" aria-hidden="true"></span>
      工作內容</h3>

    <%= simple_format(@job.description)%>

    <% if @job.requirement %>
    <h3><span class="glyphicon glyphicon glyphicon-ok" aria-hidden="true"></span>
      應徵條件</h3>
    <p>
      <%= simple_format(@job.requirement)%>
    </p>
    <% end %>

    <% if @job.apply_info %>
    <h3><span class="glyphicon glyphicon glyphicon-envelope" aria-hidden="true"></span>
      應徵方式</h3>
    <p>
      <%= simple_format(@job.apply_info)%>
    </p>
    <% end %>


    <%= link_to 'Back', jobs_path , class:"back-section btn btn-default"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>a Job on Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "common/navbar" %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/root.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>a Job on Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "common/navbar" %>
  <%= yield %>
</body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="col-md-8 col-md-offset-2 page">
    <h2>關於 Job on Rails</h2>
    <p>
      一個幫助Ruby or Ruby on Rails工程師找到工作的網站。
    </p>
    <p>
      徵才者可以在使用Facebook登入後刊登徵才訊息，您的徵才訊息只會儲存在本站90天， 
    </p>
    <p>
      去吧，我把Rails的工作都放在那裡了，去找一份Rails的工作吧！
    </p>

    <h2>About Job on Rails</h2>
    <p>
      A Web help Taiwan Rails Developer to get a job.
    </p>
    <p>
      You can post job information after sign up.
    </p>
    <p>
      Get a Job or Help your friend get a job, Enjoy!
    </p>
    <p>
      <%= link_to "Vinn" , "https://vinn.tw" %>
    </p>
    <a href="https://github.com/viflin/JobOnRails"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/a6677b08c955af8400f44c6298f40e7d19cc5b2d/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677261795f3664366436642e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png"></a>
  </div>
</div>